name: Code Style & Tests  # 更新名称

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 linter
        run: flake8 . --count --show-source --statistics

      # 新增单元测试步骤
      - name: Run unit tests with pytest
        run: pytest tests/ -v